// Generated by BUCKLESCRIPT VERSION 1.2.2+dev , PLEASE EDIT WITH CARE
'use strict';


function ascii_explode(s) {
  return s.split("");
}

exports.ascii_explode = ascii_explode;
/* No side effect */
